Tensor Shapes & Broadcasting (DSA for AI & ML)

What Is a Tensor? (Clear Mental Model)

| Name   | Dimension | Example Shape |
| ------ | --------- | ------------- |
| Scalar | 0D        | `()`          |
| Vector | 1D        | `(5,)`        |
| Matrix | 2D        | `(3, 4)`      |
| Tensor | ND        | `(2, 3, 4)`   |


Scalar + Vector

In [3]:
import numpy as np

a = np.array([1, 2, 3])
b = 10

print(a + b)

# Computer pretends:

# b → [10, 10, 10]


[11 12 13]


In [4]:
M = np.array([[1,2,3],
              [4,5,6]])

v = np.array([10, 20, 30])

print(M + v)


[[11 22 33]
 [14 25 36]]
