In [1]:
import torch
print(torch.__version__)

2.10.0+cpu


In [2]:
if torch.cuda.is_available():
  print("GPU is is_available")
  print(f"Using GPU : {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU")

GPU not available. Using CPU


Creating a Tensor

In [5]:
#usig empty tensor
x = torch.empty(2,3)  
# x = torch.empty(size=(2,3))  # another way to create empty tensor
# where 2 is number of rows and 3 is number of columns
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
# Check the Type and Shape of the tensor
print(f"Type of x : {x.dtype}")
print(f"Shape of x : {x.shape}")

Type of x : torch.float32
Shape of x : torch.Size([2, 3])


In [7]:
#Using Zeros tensor
x = torch.zeros(2,3)
print(x)


tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
# Using Ones tensor
x = torch.ones(2,3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [9]:
# Using Random tensor
x = torch.rand(2,3)
print(x)

tensor([[0.2746, 0.2570, 0.2186],
        [0.4768, 0.0379, 0.6827]])


In [11]:
# Use Seed for reproducibility
torch.manual_seed(42)
x = torch.rand(2,3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [12]:
torch.manual_seed(42)
x = torch.rand(2,3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [13]:
# Using Tensor
x = torch.tensor([[1,2,3],[4,5,6]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [14]:
# Other way to create tensor

# 1. arange - like python's range but returns a tensor
x = torch.arange(0,10,2)  # start, end, step
print(x)

# 2. linspace - returns evenly spaced numbers over a specified interval
x = torch.linspace(0,1,5)  # start, end, number of
print(x)

# 3. eye - returns a 2-D tensor with ones on the diagonal and zeros elsewhere
x = torch.eye(5)  # size of the square matrix
print(x)

# 4. diag - returns a diagonal tensor
x = torch.diag(torch.ones(5))  # size of the square matrix
print(x)

# 5. full - returns a tensor filled with a specified value
x = torch.full((2,3), 7)  # size and value
print(x)

tensor([0, 2, 4, 6, 8])
tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[7, 7, 7],
        [7, 7, 7]])


Tesor Shapes

In [15]:
x = torch.tensor([[1,2,3],[4,5,6]])
print(x)
print(x.dtype)
print(x.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.int64
torch.Size([2, 3])


In [16]:
# Making a tensor with same sape as another tensor using empty_like, zeros_like, ones_like functions
x = torch.empty_like(x)
print(x)

tensor([[4618230892912,             0,             0],
        [            0,             0,             0]])


In [17]:
# torch.zeros_like(x)
# torch.ones_like(x)
print(torch.zeros_like(x))
print(torch.ones_like(x))

tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[1, 1, 1],
        [1, 1, 1]])


Tensor Data Types

In [19]:
# find the data type of the tensor
print(x.dtype)

torch.int64


In [20]:
# Assigning the data type of the tensor
x = torch.tensor([1.0,2.0,3.0], dtype=torch.int32)
print(x)
print(x.dtype)

tensor([1, 2, 3], dtype=torch.int32)
torch.int32


In [21]:
torch.tensor([1,2,3], dtype=torch.float32)
print(x)
print(x.dtype)

tensor([1, 2, 3], dtype=torch.int32)
torch.int32


In [23]:
# change the data type of given data using .to() method
x = x.to(torch.float32)
print(x)

tensor([1., 2., 3.])


Mathematical Operations

In [24]:
x = torch.rand(2,2)
x

tensor([[0.2566, 0.7936],
        [0.9408, 0.1332]])

In [25]:
# Addition
x+2

tensor([[2.2566, 2.7936],
        [2.9408, 2.1332]])

In [28]:
# Subtraction
x-2
print(x)

# Multiplication
x*2
print(x)

# Division
x/2
print(x)

tensor([[0.2566, 0.7936],
        [0.9408, 0.1332]])
tensor([[0.2566, 0.7936],
        [0.9408, 0.1332]])
tensor([[0.2566, 0.7936],
        [0.9408, 0.1332]])


In [29]:
# Abs
x = torch.tensor([-1,-2,3])
print(x)
print(torch.abs(x))


tensor([-1, -2,  3])
tensor([1, 2, 3])


In [31]:
# Negative
torch.neg(x)

tensor([ 1,  2, -3])

In [32]:
# round
x = torch.tensor([1.2, 2.7, 3.1])
print(x)
print(torch.round(x))

tensor([1.2000, 2.7000, 3.1000])
tensor([1., 3., 3.])


In [33]:
# Ceil 
x = torch.tensor([1.2, 2.7, 3.1])
print(x)
print(torch.ceil(x))

tensor([1.2000, 2.7000, 3.1000])
tensor([2., 3., 4.])


In [34]:
# FLoor
x = torch.tensor([1.2, 2.7, 3.1])
print(x)
print(torch.floor(x))

tensor([1.2000, 2.7000, 3.1000])
tensor([1., 2., 3.])


In [35]:
# Clamp
x = torch.tensor([-1.2, 0.5, 2.7, 3.1])
print(x)    
print(torch.clamp(x, min=0.0, max=2.0))

tensor([-1.2000,  0.5000,  2.7000,  3.1000])
tensor([0.0000, 0.5000, 2.0000, 2.0000])


Reduction Operation